### ISSUE TITLE
npm install出现问题,求解答

### ISSUE THREAD

**Issue by 2lei** [airen/jsStudy#1]
npm无法正确安装
git bash 

```
npm install
npm WARN package.json gulp-workflow@0.0.1 No repository field.
npm WARN unmet dependency C:\Users\Xman\Desktop\js study\jsStudy\node_modules\browser-sync\node_modules\localtunnel requires yargs@'3.29.0' but will load
npm WARN unmet dependency C:\Users\Xman\Desktop\js study\jsStudy\node_modules\browser-sync\node_modules\yargs,
npm WARN unmet dependency which is version 4.7.1
npm WARN unmet dependency C:\Users\Xman\Desktop\js study\jsStudy\node_modules\gulp-inline-css\node_modules\inline-css\node_modules\cheerio\node_modules\htmlparser2 requires entities@'1.0' but will load
npm WARN unmet dependency C:\Users\Xman\Desktop\js study\jsStudy\node_modules\gulp-inline-css\node_modules\inline-css\node_modules\cheerio\node_modules\entities,
npm WARN unmet dependency which is version 1.1.1
```

```
$ gulp
[16:00:13] Failed to load external module babel-register
[16:00:13] Failed to load external module babel-core/register
[16:00:13] Failed to load external module babel/register
C:\Users\Xman\Desktop\js study\jsStudy\gulpfile.babel.js:8
import gulp          from 'gulp'
^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (C:\Users\Xman\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (C:\Users\Xman\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:193:16)
    at module.exports (C:\Users\Xman\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\node_modules\flagged-respawn\index.js:17:3
```

node版本 v4.4.3
npm版本 v2.15.1

**Comment by airen** [comment]
你换cnpm试试
